#FROM openjdk:8-alpine
# Imagen de base openjdk 11, en caso de usar java 8 mirar la primera linea
#FROM openjdk:11
FROM eclipse-temurin:11-alpine
#Define las variables de ambiente
ENV MYSQL_DB_HOST=mysql-library
ENV MYSQL_DB_PORT=3306
ENV MYSQL_DB_USERNAME=root
ENV MYSQL_DB_PASSWORD=password
ENV RABBITMQ_HOST=rabbitmq
# Copia el jar ejecutable
COPY target/backend-store-0.0.1-SNAPSHOT.jar /usr/share/app.jar
# Lanza el ejecutable usando java 
CMD ["java", "-jar", "/usr/share/app.jar"]
# Expone el puerto 8081
EXPOSE 8082